require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const cookieParser = require('cookie-parser');
const { rateLimit } = require('express-rate-limit');
const { sequelize } = require('./models');
const app = express();
app.set('trust proxy', 1);
const origins = (process.env.ALLOWED_ORIGINS || process.env.FRONTEND_URL || 'http://localhost:5173').split(',').map(x => x.trim());
app.use(helmet());
app.use(cors({ origin: (origin, cb) => cb(null, !origin || origins.includes(origin)), credentials: true }));
app.use(express.json({ limit: '32kb' }));
app.use(cookieParser());
app.use((req, res, next) => {
  if (!['GET', 'HEAD', 'OPTIONS'].includes(req.method) && req.get('origin') && !origins.includes(req.get('origin'))) return res.status(403).json({ message: 'Origin not allowed.' });
  next();
});
app.get('/health', async (req, res) => { try { await sequelize.authenticate(); res.json({ status: 'ok' }); } catch { res.status(503).json({ status: 'database_unavailable' }); } });
app.get('/', (req, res) => res.json({ service: 'PROMOTtv API' }));
app.use('/api', rateLimit({ windowMs: 15 * 60 * 1000, limit: 500, standardHeaders: 'draft-8', legacyHeaders: false, message: { message: 'Too many requests. Please try again later.' } }));
const authLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 25, message: { message: 'Too many sign-in attempts. Try again in 15 minutes.' } });
app.use('/api/auth/login', authLimit); app.use('/api/auth/signup', authLimit);
app.use('/api/auth', require('./routes/userroutes'));
app.use('/api/creator', require('./routes/creatorRoutes'));
app.use('/api/workspace', require('./routes/workspace'));
app.use('/api/payments', require('./routes/payments'));
app.use((req, res) => res.status(404).json({ message: 'API route not found.' }));
app.use((error, req, res, next) => {
  if (res.headersSent) return next(error);
  const status = error.status || (error.name === 'SequelizeUniqueConstraintError' ? 409 : 500);
  if (status >= 500) console.error('Request failed:', error.name);
  res.status(status).json({ message: status === 409 ? 'This record already exists or was already processed.' : status >= 500 ? 'The service is temporarily unavailable. Please try again.' : error.message });
});
module.exports = app;
