import usePageMotion from '../lib/usePageMotion';
import { Link } from 'react-router-dom';
import { ArrowUpRightIcon, ArrowRightIcon, PlayIcon, CheckIcon, ShieldCheckIcon, GlobeAltIcon, SparklesIcon } from '@heroicons/react/24/outline';
import Navbar from '../components/PublicNav';
import Brand from '../components/Brand';
const steps = [['01', 'Make yourself at home', 'Create an earner account and add your social profile.'], ['02', 'Find your next task', 'Discover campaigns, follow the instructions, and submit your proof.'], ['03', 'Turn effort into rewards', 'Approved tasks add to your balance. Track every reward in your wallet.']];
export default function Landing() {
  const motionRoot = usePageMotion('landing');
  return <div ref={motionRoot} className="marketing"><Navbar/><main>
    <section className="hero-section container"><div className="hero-copy"><span className="eyebrow"><span className="live-dot"/> A little action. A new opportunity.</span><h1>Your everyday<br/>scroll, with<br/><span>more purpose.</span></h1><p>Discover creators. Complete simple social tasks.<br className="desktop-break"/> Get rewarded for the part you play.</p><div className="actions"><Link to="/signup/earner" className="button">Start earning <ArrowUpRightIcon/></Link><Link to="/signup/creator" className="text-link">Grow your audience <ArrowRightIcon/></Link></div><div className="hero-note"><ShieldCheckIcon/> Free to join <span>·</span> Clear task rewards <span>·</span> Built for you</div></div>
    <div className="hero-art" aria-label="Illustration of the PROMOTtv task experience"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="floating-platform youtube">▶</span><span className="floating-platform instagram">◎</span><span className="floating-platform tiktok">♪</span><div className="preview-card"><div className="preview-top"><span className="mini-mark">p▶</span><span>Your next opportunity</span><span className="preview-dots">•••</span></div><div className="preview-heading"><span className="eyebrow">SMALL ACTIONS. REAL PROGRESS.</span><h2>Make your time<br/>count.</h2><span className="illustration-label">Platform preview</span></div><div className="preview-task"><span className="platform-icon red"><PlayIcon/></span><div><strong>Discover a new video</strong><small>Watch · Explore · Submit proof</small></div><ArrowUpRightIcon/></div><div className="preview-task"><span className="platform-icon violet"><SparklesIcon/></span><div><strong>Meet your next creator</strong><small>Find something worth following</small></div><ArrowUpRightIcon/></div><div className="preview-bottom"><span><CheckIcon/> Your effort, recognised</span><span>USD rewards</span></div></div><div className="floating-note"><span className="check-bubble"><CheckIcon/></span><div><strong>A little progress, every day.</strong><small>One completed task at a time.</small></div></div></div></section>
    <section className="platform-strip"><div className="container"><span>A world of content to discover</span><div>YouTube</div><div>instagram</div><div>TikTok</div><div>facebook</div></div></section>
    <section id="how-it-works" className="container section"><div className="section-heading"><div><span className="eyebrow">GET INTO YOUR FLOW</span><h2>Three steps.<br/>Plenty of possibility.</h2></div><p>No complicated setup. Just a clear path<br/>from your first task to your next reward.</p></div><div className="steps">{steps.map(([number, title, description]) => <article key={number}><span className="step-number">{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section id="creators" className="container"><div className="creator-banner"><div><span className="eyebrow">FOR CREATORS & BRANDS</span><h2>You make the content.<br/>Let’s help it travel.</h2><p>Launch a campaign, choose your audience actions, and keep your spend and results in one place.</p><Link to="/signup/creator" className="button mint">Create your first campaign <ArrowUpRightIcon/></Link></div><div className="campaign-visual"><GlobeAltIcon/><span className="campaign-chip chip-one">Your next viewer</span><span className="campaign-chip chip-two">Your next follower</span><span className="campaign-chip chip-three">Your next community</span></div></div></section>
    <section className="container section faq-preview"><div><span className="eyebrow">GOOD TO KNOW</span><h2>Clear from the start.</h2><Link className="text-link" to="/faq">Explore the FAQs <ArrowRightIcon/></Link></div><div><details><summary>When can I withdraw?</summary><p>Request a crypto payout when your approved balance reaches $10 and two people have registered through your referral link. Finance reviews every request.</p></details><details><summary>How are rewards approved?</summary><p>Submit evidence after completing a task. Our moderation team reviews it before the reward is added to your wallet.</p></details><details><summary>Do I need to stay active?</summary><p>Yes. A full UTC day without a task submission leads to a 30% deduction from your available earnings. Your registration day is excluded. Pending submissions count as activity.</p></details></div></section>
  </main><footer className="container footer"><Brand/><span>© {new Date().getFullYear()} PROMOTtv</span><Link to="/faq">Help & platform rules</Link><Link to="/login">Staff login</Link></footer></div>;
}
