import usePageMotion from '../lib/usePageMotion';
import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import { ArrowUpRightIcon, ArrowRightOnRectangleIcon, Bars3Icon, XMarkIcon, Squares2X2Icon, WalletIcon, UserGroupIcon, Cog6ToothIcon, MegaphoneIcon, ClipboardDocumentCheckIcon, ShieldCheckIcon, PlusIcon, CheckIcon } from '@heroicons/react/24/outline';
import Brand from '../components/Brand';
import StaffActions from '../components/StaffActions';
import SubmissionHistory from '../components/SubmissionHistory';
import PaymentRecovery from '../components/PaymentRecovery';
import { Dialog, DialogPanel, DialogTitle } from '@headlessui/react';
import { api, dashboard, message, saveSession, usd } from '../lib/api';
const titles = { overview: 'Overview', tasks: 'Discover tasks', campaigns: 'Your campaigns', wallet: 'Wallet & payments', referrals: 'Invite friends', membership: 'Membership', settings: 'Account settings', members: 'Member accounts', reviews: 'Review submissions', finance: 'Finance', audit: 'Activity log' };
const icons = { overview: Squares2X2Icon, tasks: ClipboardDocumentCheckIcon, campaigns: MegaphoneIcon, wallet: WalletIcon, referrals: UserGroupIcon, membership: ShieldCheckIcon, settings: Cog6ToothIcon, members: UserGroupIcon, reviews: ClipboardDocumentCheckIcon, finance: WalletIcon, audit: ShieldCheckIcon };
const label = text => String(text).replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase());
function Empty({ title, text }) { return <div className="empty"><span>↗</span><h3>{title}</h3><p>{text}</p></div>; }
function Status({ value }) { return <span className={'status ' + value}>{label(value)}</span>; }
function Ledger({ transactions = [] }) {
  return transactions.length ? <div className="table-scroll"><table><thead><tr><th>Activity</th><th>Date</th><th>Method</th><th>Amount</th></tr></thead><tbody>{transactions.map(item => <tr key={item.id}><td><strong>{item.note}</strong><small>Transaction #{item.id}{item.userId ? ' · Member #' + item.userId : ''}</small></td><td>{new Date(item.createdAt).toLocaleDateString()}</td><td>{label(item.method)}</td><td className={item.type === 'credit' ? 'positive' : ''}>{item.type === 'credit' ? '+' : '−'}{usd(item.amount, 6)}</td></tr>)}</tbody></table></div> : <Empty title="A fresh start" text="Your transactions will appear here as you use the platform."/>;
}
export default function Workspace({ role }) {
  const navigate = useNavigate();
  const [params, setParams] = useSearchParams();
  const [data, setData] = useState(null);
  const [tasks, setTasks] = useState([]);
  const [admin, setAdmin] = useState(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [menu, setMenu] = useState(false);
  const [creating, setCreating] = useState(false);
  const [proofTask, setProofTask] = useState(null);
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const [paymentState, setPaymentState] = useState('');
  const tab = params.get('tab') || 'overview';
  const motionRoot = usePageMotion('workspace', tab, Boolean(data));
  const load = useCallback(async () => {
    try {
      const { data: overview } = await api.get('/workspace/overview');
      const actual = overview.user.role;
      if ((role === 'staff' && ['earner', 'creator'].includes(actual)) || (role !== 'staff' && actual !== role)) { navigate(dashboard(actual), { replace: true }); return; }
      setData(overview);
      if (role === 'staff') { const staffData = (await api.get('/workspace/admin')).data; setAdmin(staffData); setTasks(staffData.tasks || []); }
      else setTasks((await api.get(role === 'creator' ? '/creator/tasks' : '/workspace/tasks')).data);
      setError('');
    } catch (error) {
      if (error.response?.status === 401) { sessionStorage.removeItem('promot_token'); navigate('/login', { replace: true }); }
      else setError(message(error));
    }
  }, [role, navigate]);
  useEffect(() => { let mounted = true; Promise.resolve().then(() => { if (mounted) load(); }); return () => { mounted = false; }; }, [load]);
  async function action(fn, success) {
    setBusy(true);
    try { await fn(); if (success) toast.success(success); await load(); return true; }
    catch (error) { toast.error(message(error)); return false; }
    finally { setBusy(false); }
  }
  async function verifyPayment() {
    setPaymentState('Verifying payment…');
    const ok = await action(() => api.post('/payments/verify', { transactionId: params.get('transaction_id') }), 'Payment verified.');
    setPaymentState(ok ? 'Payment verified and recorded.' : 'Could not verify this payment. You can safely try again.');
    if (ok) setParams({ tab: 'wallet' });
  }
  function select(next) { setParams({ tab: next }); setMenu(false); setCreating(false); setSearch(''); }
  async function logout() {
    if (await action(() => api.post('/auth/logout'))) { sessionStorage.removeItem('promot_token'); localStorage.removeItem('ppt_user'); navigate('/login'); }
  }
  if (!data) return <div className="loading-page"><Brand/>{error ? <><h2>We couldn’t load your workspace.</h2><p role="alert">{error}</p><button className="button" onClick={load}>Try again</button><Link to="/login">Back to sign in</Link></> : <><div className="spinner"/><p role="status">Opening your workspace…</p></>}</div>;
  const { user } = data;
  const staff = role === 'staff';
  const earner = role === 'earner';
  const moderation = ['moderator', 'manager'].includes(user.role);
  const finance = ['finance', 'manager'].includes(user.role);
  const navigation = earner ? ['overview', 'tasks', 'wallet', 'referrals', 'settings'] : staff ? ['overview', 'members', ...(moderation ? ['reviews'] : []), ...(finance ? ['finance'] : []), ...(user.role === 'manager' ? ['campaigns', 'audit'] : []), 'settings'] : ['overview', 'campaigns', 'wallet', 'membership', 'settings'];
  const current = navigation.includes(tab) ? tab : 'overview';
  const referralUrl = window.location.origin + '/signup/earner?ref=' + encodeURIComponent(user.referralCode || '');
  const visibleTasks = tasks.filter(task => (filter === 'all' || task.platform.startsWith(filter)) && (task.title + task.platform).toLowerCase().includes(search.toLowerCase()));
  const activityToday = data.submissions.some(s => s.status !== 'rejected' && s.createdAt.slice(0, 10) === new Date().toISOString().slice(0, 10));
  const hasSocial = ['facebookLink', 'youtubeLink', 'instagramLink', 'tiktokLink'].some(key => user[key]);
  async function checkout(body) { await action(async () => { const result = await api.post('/payments/checkout', body); window.location.assign(result.data.url); }); }
  return <div ref={motionRoot} className="workspace"><aside className={'sidebar ' + (menu ? 'is-open' : '')}><div className="sidebar-brand"><Brand/><button className="menu-toggle" aria-label="Close navigation" onClick={() => setMenu(false)}><XMarkIcon/></button></div><span className="sidebar-caption">{staff ? label(user.role) + ' workspace' : label(role) + ' workspace'}</span><nav>{navigation.map(key => { const Icon = icons[key]; return <button key={key} className={current === key ? 'active' : ''} onClick={() => select(key)}><Icon/>{titles[key]}{key === 'reviews' && admin?.submissions.length > 0 && <span className="nav-count">{admin.submissions.length}</span>}</button>; })}</nav><div className="sidebar-bottom"><div className="sidebar-help"><span>Keep moving forward.</span><p>A little progress goes a long way.</p><Link to="/faq">Help & platform rules ↗</Link></div><button className="logout" onClick={logout} disabled={busy}><ArrowRightOnRectangleIcon/> Sign out</button></div></aside>{menu && <button className="sidebar-backdrop" aria-label="Close navigation" onClick={() => setMenu(false)}/>}
  <div className="workspace-body"><header className="workspace-header"><div><button className="menu-toggle" onClick={() => setMenu(!menu)} aria-label="Open navigation" aria-expanded={menu}><Bars3Icon/></button><span className="breadcrumb">Workspace <span>/</span> <strong>{titles[current]}</strong></span></div><div className="user-badge"><span className="avatar">{user.fullName.slice(0, 1).toUpperCase()}</span><div><strong>{user.fullName}</strong><small>{label(user.role)} account</small></div></div></header><main className="workspace-main">
    {error && <div className="notice error" role="alert">{error} <button onClick={load}>Retry</button></div>}
    {params.get('transaction_id') && <div className="notice"><span>{paymentState || 'Returned from checkout. Verify your payment to update your account.'}</span><button className="button small" disabled={busy} onClick={verifyPayment}>Verify payment</button></div>}
    <div className="page-heading"><div><span className="eyebrow">{current === 'overview' ? 'LET’S MAKE TODAY COUNT' : 'YOUR PROMOTtv WORKSPACE'}</span><h1>{current === 'overview' ? 'Hello, ' + user.fullName.split(' ')[0] + '.' : titles[current]}</h1><p>{current === 'overview' ? earner ? 'Your next opportunity is waiting. Pick up where you left off.' : staff ? 'A clear view of the community and the work ahead.' : 'A little more reach. A little more possibility.' : 'Everything you need, right where you need it.'}</p></div>{!earner && (!staff || user.role === 'manager') && ['overview', 'campaigns'].includes(current) && <button className="button" onClick={() => { select('campaigns'); setCreating(true); }}><PlusIcon/> New campaign</button>}</div>
    {current === 'overview' && <><div className="stats-grid"><article className="stat-card dark"><span>{staff ? 'Member accounts' : 'Available balance'}</span><strong>{staff ? admin?.users.length || 0 : usd(user.balance)}</strong><small>{staff ? 'Latest 500 accounts' : earner ? 'Approved rewards · USD' : 'Ready for your next campaign'}</small><WalletIcon/></article><article className="stat-card"><span>{staff ? 'Awaiting review' : earner ? 'Tasks approved' : 'Campaigns created'}</span><strong>{staff ? admin?.submissions.length || 0 : earner ? data.submissions.filter(s => s.status === 'approved').length : tasks.length}</strong><small>{earner ? data.submissions.filter(s => s.status === 'pending').length + ' submissions in review' : 'Your activity at a glance'}</small></article><article className="stat-card"><span>{staff ? 'Pending payouts' : earner ? 'Your referrals' : 'Current membership'}</span><strong>{staff ? admin?.withdrawals.filter(w => w.status === 'pending').length || 0 : earner ? data.referrals + ' / 2' : data.activePlan}</strong><small>{earner ? 'Two registrations unlock withdrawals' : staff ? 'Finance review required' : 'Built around your goals'}</small></article></div>
      {earner && <div className="daily-banner"><span className="daily-icon"><CheckIcon/></span><div><strong>{activityToday ? 'You’ve made progress today.' : 'Make time for one task today.'}</strong><p>{activityToday ? 'Your submission is recorded for today (UTC).' : 'Inactive UTC days deduct 30% of your available earnings. Your registration day is a grace day.'}</p></div><button className="text-link" onClick={() => select('tasks')}>Find a task <ArrowUpRightIcon/></button></div>}
      <div className="dashboard-columns"><section className="panel"><div className="panel-heading"><h2>{staff ? 'Your workspace' : earner ? 'Fresh opportunities' : 'Recent campaigns'}</h2><button className="text-link" onClick={() => select(staff ? 'members' : earner ? 'tasks' : 'campaigns')}>View all ↗</button></div>{staff ? <Empty title="A community worth looking after" text="Use the navigation to manage the areas available to your staff role."/> : tasks.length ? <div className="compact-tasks">{tasks.slice(0, 3).map(task => <div key={task.id}><span className={'platform-icon ' + (task.platform.startsWith('youtube') ? 'red' : 'violet')}>{task.platform.startsWith('youtube') ? '▶' : '↗'}</span><div><strong>{task.title}</strong><small>{label(task.platform)}</small></div>{earner ? <b>{usd(task.reward, 6)}</b> : <Status value={task.status}/>}</div>)}</div> : <Empty title={earner ? 'New opportunities are on their way' : 'Your first campaign starts here'} text={earner ? 'Published campaigns will appear here. Check back soon.' : 'Choose an action, set a budget, and put your content out there.'}/>}</section><section className="panel quick-card"><span className="eyebrow">{earner ? 'BETTER TOGETHER' : 'ROOM TO GROW'}</span><h2>{earner ? 'Good things are worth sharing.' : 'Make your next move.'}</h2><p>{earner ? 'Invite two friends to join and unlock withdrawals once your balance reaches $10.' : staff ? 'Each staff action is recorded. Keep account decisions clear and consistent.' : 'Explore creator memberships and save on each campaign.'}</p><button className="button secondary" onClick={() => select(earner ? 'referrals' : staff ? 'members' : 'membership')}>{earner ? 'Invite a friend' : staff ? 'View members' : 'Explore plans'} <ArrowUpRightIcon/></button></section></div>
      <section className="panel"><div className="panel-heading"><h2>Recent activity</h2></div><Ledger transactions={data.transactions.slice(0, 5)}/></section></>}
    {current === 'tasks' && <>{!hasSocial && <div className="notice">Add your social profile before submitting a task. <button className="text-link" onClick={() => select('settings')}>Go to Settings ↗</button></div>}<div className="task-toolbar"><div className="filters">{['all', 'youtube', 'instagram', 'tiktok', 'facebook', 'app'].map(p => <button key={p} className={filter === p ? 'selected' : ''} onClick={() => setFilter(p)}>{p === 'all' ? 'All tasks' : label(p)}</button>)}</div><input aria-label="Search tasks" placeholder="Search opportunities…" value={search} onChange={e => setSearch(e.target.value)}/></div>{visibleTasks.length ? <div className="task-grid">{visibleTasks.map(task => <article className="panel task-card" key={task.id}><div className="task-card-top"><span className={'platform-icon ' + (task.platform.startsWith('youtube') ? 'red' : 'violet')}>{task.platform.startsWith('youtube') ? '▶' : '↗'}</span><span className="status">{label(task.type)} campaign</span></div><h2>{task.title}</h2><p>{label(task.platform)} · {task.remaining} places available</p><div className="reward"><span>Reward after approval</span><strong>{usd(task.reward, 6)}</strong></div><button className="button secondary full" onClick={() => setProofTask(task)}>View task <ArrowUpRightIcon/></button></article>)}</div> : <section className="panel"><Empty title="No matching tasks yet" text="Try another filter or check back for new campaigns."/></section>}</>}
    {current === 'tasks' && <SubmissionHistory submissions={data.submissions}/>}
    {current === 'campaigns' && <>{creating && <CampaignForm testing={!staff && data.creatorPaymentsPaused} pricing={data.pricing} discount={staff ? 0 : data.plans[data.activePlan].discount} busy={busy} staff={staff} onCancel={() => setCreating(false)} onSubmit={async body => { if (await action(() => api.post(staff ? '/workspace/admin/tasks' : '/creator/tasks', body), 'Campaign published.')) setCreating(false); }}/>}<section className="panel"><div className="panel-heading"><h2>{staff ? 'Platform campaigns' : 'Campaign performance'}</h2><button className="button small" onClick={() => setCreating(true)}>New campaign <PlusIcon/></button></div>{tasks.length ? <div className="table-scroll"><table><thead><tr><th>Campaign</th><th>Budget</th><th>Places taken</th><th>Status</th></tr></thead><tbody>{tasks.map(task => <tr key={task.id}><td><strong>{task.title}</strong><small>{label(task.platform)}</small></td><td>{usd(task.budget)}</td><td>{task.count - task.remaining} / {task.count}</td><td><Status value={task.status}/></td></tr>)}</tbody></table></div> : <Empty title={staff ? 'Publish a platform opportunity' : 'Your story deserves an audience'} text={staff ? 'Platform campaigns use a 20% reward allocation and do not debit a creator wallet.' : 'Create your first campaign to start tracking its progress here.'}/>}</section></>}
    {current === 'wallet' && <><div className="dashboard-columns"><section className="panel wallet-summary"><span className="eyebrow">YOUR AVAILABLE BALANCE</span><h2>{usd(user.balance, 6)}</h2><p>{earner ? 'Approved rewards, ready for your next step.' : 'Campaign funds, safely recorded in your wallet.'}</p>{earner && <div className="notice">Minimum $10 · {data.referrals}/2 referrals · USDT (TRC20)</div>}</section><section className="panel"><h2>{earner ? 'Request a withdrawal' : 'Add campaign funds'}</h2><form onSubmit={async event => { event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form)); if (earner) { if (await action(() => api.post('/workspace/withdrawals', { ...body, network: 'USDT (TRC20)' }), 'Withdrawal submitted for finance review.')) form.reset(); } else await checkout({ ...body, purpose: 'wallet' }); }}><label>Amount (USD)<input name="amount" type="number" min={earner ? 10 : 1} max={earner ? Math.floor(Number(user.balance) * 100) / 100 : 10000} step=".01" required placeholder="0.00"/></label>{earner && <><label>USDT wallet address (TRC20)<input name="address" required pattern="T[1-9A-HJ-NP-Za-km-z]{33}" placeholder="Your TRON wallet address"/></label><label className="checkbox"><input type="checkbox" required/><span>I have checked the wallet address and TRC20 network.</span></label></>}<button className="button full" disabled={busy || (earner ? Number(user.balance) < 10 || data.referrals < 2 : !data.paymentsEnabled)}>{earner ? 'Request withdrawal' : 'Continue to Flutterwave'}<ArrowUpRightIcon/></button>{!earner && !data.paymentsEnabled && <p className="field-help">Payments are being configured. Funding will be available soon.</p>}{earner && <p className="field-help">Finance reviews and sends approved payouts manually. Submission does not mean the transfer is complete.</p>}</form></section></div>{!earner && <PaymentRecovery onVerified={load}/>}<section className="panel"><h2>Transaction history</h2><Ledger transactions={data.transactions}/></section>{earner && <section className="panel"><h2>Withdrawal requests</h2>{data.withdrawals.length ? data.withdrawals.map(w => <div className="list-row" key={w.id}><div><strong>{usd(w.amount)} · {w.network}</strong><small>{w.address}</small>{w.txHash && <small>Transaction: {w.txHash}</small>}</div><Status value={w.status}/></div>) : <Empty title="No withdrawals yet" text="Your requests and their progress will appear here."/ >}</section>}</>}
    {current === 'referrals' && <div className="dashboard-columns"><section className="panel referral-panel"><span className="eyebrow">GROW TOGETHER</span><h2>A good opportunity<br/>is better shared.</h2><p>Two people need to register using your link before you can withdraw. Share it with friends who might enjoy the platform.</p><label>Your invitation link<input readOnly value={referralUrl}/></label><button className="button" onClick={async () => { try { await navigator.clipboard.writeText(referralUrl); toast.success('Invitation link copied.'); } catch { toast.error('Select the invitation link above and copy it.'); } }}>Copy invitation link <ArrowUpRightIcon/></button></section><section className="panel"><span className="eyebrow">YOUR PROGRESS</span><div className="referral-count">{data.referrals}<span>/ 2</span></div><progress max="2" value={Math.min(data.referrals, 2)}/><h3>{data.referrals >= 2 ? 'Referral requirement complete' : 'Every invitation is a new beginning'}</h3><p>Registered, unsuspended referrals count. You still need an approved balance of at least $10 to withdraw.</p></section></div>}
    {current === 'membership' && <><p className="notice">Your active plan: <strong>{data.activePlan}</strong>. Memberships last 30 days and do not renew automatically. Changing to another plan starts a new 30-day term without credit for unused time.</p><div className="plans-grid">{Object.entries(data.plans).map(([name, plan]) => <section className={'panel plan-card ' + (name === 'Premium' ? 'featured' : '')} key={name}><span className="eyebrow">{name === 'Premium' ? 'A LITTLE MORE MOMENTUM' : name === 'Diamond' ? 'MORE ROOM TO GROW' : 'START YOUR JOURNEY'}</span><h2>{name}</h2><div className="plan-price">{usd(plan.monthly)}<small>/ 30 days</small></div><p>{plan.discount}% off campaign actions</p><ul><li><CheckIcon/> Campaign dashboard</li><li><CheckIcon/> Verified wallet payments</li><li><CheckIcon/> Clear transaction history</li></ul><button className="button full" disabled={busy || !plan.monthly || !data.paymentsEnabled} onClick={() => checkout({ purpose: 'membership', plan: name })}>{data.activePlan === name ? plan.monthly ? 'Extend for 30 days' : 'Free plan' : plan.monthly ? 'Choose ' + name : 'Free plan'}</button></section>)}</div>{!data.paymentsEnabled && <p className="field-help">Membership checkout becomes available when platform payments are configured.</p>}</>}
    {current === 'settings' && <div className="dashboard-columns"><section className="panel"><h2>Your social profiles</h2><p>Add at least one profile before submitting tasks.</p><form onSubmit={event => { event.preventDefault(); action(() => api.patch('/workspace/profile', Object.fromEntries(new FormData(event.currentTarget))), 'Social profiles saved.'); }}>{['facebook', 'youtube', 'instagram', 'tiktok'].map(p => <label key={p}>{label(p)} profile URL<input type="url" name={p + 'Link'} defaultValue={user[p + 'Link'] || ''} placeholder="https://…" maxLength={255}/></label>)}<button className="button" disabled={busy}>Save profiles</button></form></section><section className="panel"><h2>Change password</h2><p>Updating your password signs out other sessions.</p><form onSubmit={async event => { event.preventDefault(); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form)); if (body.password !== body.confirm) return toast.error('The new passwords do not match.'); if (await action(async () => saveSession((await api.post('/auth/password', body)).data), 'Password changed.')) form.reset(); }}><label>Current password<input type="password" name="currentPassword" autoComplete="current-password" required/></label><label>New password<input type="password" name="password" autoComplete="new-password" minLength={8} required/></label><label>Confirm new password<input type="password" name="confirm" autoComplete="new-password" minLength={8} required/></label><button className="button" disabled={busy}>Update password</button></form></section></div>}
    {current === 'members' && <section className="panel"><div className="panel-heading"><h2>Member directory</h2><input aria-label="Search members" placeholder="Search name or email…" value={search} onChange={e => setSearch(e.target.value)}/></div><div className="table-scroll"><table><thead><tr><th>Member</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{admin?.users.filter(u => (u.fullName + u.email).toLowerCase().includes(search.toLowerCase())).map(u => <tr key={u.id}><td><strong>{u.fullName}</strong><small>{u.email} · #{u.id}</small></td><td>{label(u.role)}</td><td><Status value={u.suspended ? 'suspended' : u.verified ? 'verified' : 'active'}/></td><td>{user.role === 'manager' && u.id !== user.id && ['manager', 'moderator', 'finance'].includes(u.role) && <StaffActions user={u} busy={busy} action={action}/>} {['earner', 'creator'].includes(u.role) && <div className="row-actions"><button disabled={busy} onClick={() => action(() => api.patch('/workspace/admin/users/' + u.id, { suspended: !u.suspended }), 'Account updated.')}>{u.suspended ? 'Restore' : 'Suspend'}</button>{moderation && <button disabled={busy} onClick={() => action(() => api.patch('/workspace/admin/users/' + u.id, { verified: !u.verified }), 'Verification updated.')}>{u.verified ? 'Unverify' : 'Verify'}</button>}</div>}</td></tr>)}</tbody></table></div></section>}
    {current === 'reviews' && <section className="panel"><h2>Pending task evidence</h2>{admin?.submissions.length ? admin.submissions.map(s => <article key={s.id} className="review-item"><div><strong>Task #{s.taskId} · Member #{s.userId}</strong><span>{usd(s.reward, 6)}</span></div><p>{s.proof}</p><div className="row-actions"><button disabled={busy} onClick={() => action(() => api.post('/workspace/admin/submissions/' + s.id + '/review', { status: 'approved' }), 'Task approved and reward credited.')}>Approve & credit</button><button disabled={busy} onClick={() => action(() => api.post('/workspace/admin/submissions/' + s.id + '/review', { status: 'rejected' }), 'Submission rejected.')}>Reject</button></div></article>) : <Empty title="You’re all caught up" text="New task submissions will appear here for review."/ >}</section>}
    {current === 'finance' && <><section className="panel"><h2>Crypto withdrawal queue</h2><p>Send the transfer externally first. Record its transaction hash only after confirming the payout.</p>{admin?.withdrawals.length ? admin.withdrawals.map(w => <article key={w.id} className="review-item"><div><strong>#{w.id} · Member #{w.userId} · {usd(w.amount)}</strong><Status value={w.status}/></div><p>{w.network} · {w.address}</p>{w.status === 'pending' && <form onSubmit={event => { event.preventDefault(); const txHash = new FormData(event.currentTarget).get('txHash'); action(() => api.post('/workspace/admin/withdrawals/' + w.id + '/review', { status: 'paid', txHash }), 'Payout recorded.'); }}><label>Completed transfer hash<input name="txHash" required pattern="[a-fA-F0-9]{64}"/></label><div className="row-actions"><button disabled={busy}>Record paid transfer</button><button type="button" disabled={busy} onClick={() => action(() => api.post('/workspace/admin/withdrawals/' + w.id + '/review', { status: 'rejected' }), 'Withdrawal refunded.')}>Reject & refund</button></div></form>}</article>) : <Empty title="No payouts to process" text="Withdrawal requests will appear here."/ >}</section><section className="panel"><h2>Platform transactions</h2><Ledger transactions={admin?.transactions}/></section></>}
    {current === 'audit' && <section className="panel"><h2>Staff activity</h2>{admin?.audits.length ? admin.audits.map(a => <div className="list-row" key={a.id}><div><strong>{a.action}</strong><small>Staff #{a.actorId} · Record #{a.targetId} · {a.detail}</small></div><small>{new Date(a.createdAt).toLocaleString()}</small></div>) : <Empty title="No staff activity yet" text="Account decisions, task reviews and payouts are recorded here."/ >}</section>}
  </main><footer className="workspace-footer">© {new Date().getFullYear()} PROMOTtv <Link to="/faq">Help & platform rules ↗</Link></footer></div>
  {proofTask && <Dialog open onClose={() => setProofTask(null)} className="modal-backdrop"><DialogPanel className="modal panel"><button className="modal-close" aria-label="Close task" onClick={() => setProofTask(null)}><XMarkIcon/></button><span className="eyebrow">{label(proofTask.platform)}</span><DialogTitle as="h2">{proofTask.title}</DialogTitle><p>Complete the action, then submit your username and a clear description or evidence link. Rewards are credited after moderation.</p><a className="button secondary" href={proofTask.link} target="_blank" rel="noopener noreferrer">Open campaign <ArrowUpRightIcon/></a><form onSubmit={async event => { event.preventDefault(); const proof = new FormData(event.currentTarget).get('proof'); if (await action(() => api.post('/workspace/tasks/' + proofTask.id + '/submit', { proof }), 'Submitted for review.')) setProofTask(null); }}><label>Your completion evidence<textarea name="proof" minLength={10} maxLength={2000} required rows={4} placeholder="Your social username and what you completed…"/></label><button className="button full" disabled={busy || !hasSocial}>Submit for review · {usd(proofTask.reward, 6)}</button>{!hasSocial && <p className="field-help">Add a social profile in Settings first.</p>}</form></DialogPanel></Dialog>}
  </div>;
}
function CampaignForm({ pricing, discount, staff, busy, onCancel, onSubmit, testing = false }) {
  const [platform, setPlatform] = useState('youtube_view');
  const [count, setCount] = useState(1000);
  const budget = testing ? 0 : (pricing[platform] || 0) * Number(count || 0) * (1 - discount / 100);
  return <section className="panel campaign-form"><div className="panel-heading"><h2>A new opportunity starts here.</h2><button className="text-link" onClick={onCancel}>Cancel</button></div><form onSubmit={event => { event.preventDefault(); onSubmit(Object.fromEntries(new FormData(event.currentTarget))); }}><div className="form-grid"><label>Campaign title<input name="title" required maxLength={180} placeholder="Give your campaign a clear name"/></label><label>Platform & action<select name="platform" value={platform} onChange={e => setPlatform(e.target.value)}>{Object.entries(pricing).map(([key, value]) => <option key={key} value={key}>{label(key)} · {usd(value, 3)}</option>)}</select></label><label>Number of actions<input name="actionCount" type="number" value={count} onChange={e => setCount(e.target.value)} min={1} max={1000000} step={1} required/></label><label>Campaign URL<input name="socialLink" type="url" required placeholder="https://…" maxLength={2000}/></label></div><div className="campaign-total">{testing && <p role="status">Testing mode: no payment required. Earners can submit and staff can approve tasks, but these campaigns award no cash.</p>}<div><span>{testing ? 'Test campaign cost' : staff ? 'Platform-funded campaign value' : 'Total campaign budget'}</span><strong>{usd(budget, 6)}</strong></div><p>{staff ? '20%' : '50%'} allocated to task rewards{discount ? ' · ' + discount + '% membership discount applied' : ''}</p></div><button className="button" disabled={busy}>Publish campaign <ArrowUpRightIcon/></button></form></section>;
}
